apiVersion: v1
kind: Pod
metadata:
  name: envoy-wasm
  labels:
    app: envoy
spec:
  containers:
  - name: envoy
    image: my-envoy-wasm:latest
    imagePullPolicy: Never
    ports:
    - containerPort: 10000
---
apiVersion: v1
kind: Service
metadata:
  name: envoy-service
spec:
  type: NodePort
  selector:
    app: envoy
  ports:
  - port: 80
    targetPort: 10000
    nodePort: 30000
